import { Document, Page, Text, View, StyleSheet } from "@react-pdf/renderer";
import type { DailyBriefingData } from "@/features/daily-briefing/types/briefing.types";

const styles = StyleSheet.create({
  page: { padding: 24, fontSize: 10, color: "#111" },
  banner: { fontSize: 9, letterSpacing: 2, marginBottom: 10, color: "#666" },
  heading: { fontSize: 16, marginBottom: 6 },
  subheading: { fontSize: 12, marginTop: 10, marginBottom: 4 },
  line: { marginBottom: 4 },
  footer: { position: "absolute", bottom: 20, left: 24, right: 24, fontSize: 9, color: "#666" },
});

export function BriefingPdfDocument({ data }: { data: DailyBriefingData }) {
  return (
    <Document>
      <Page size="A4" style={styles.page}>
        <Text style={styles.banner}>UNCLASSIFIED // OPEN SOURCE</Text>
        <Text style={styles.heading}>Daily Intelligence Briefing</Text>
        <Text style={styles.line}>
          Threat: {data.threatLevel} | Escalation Score: {data.escalationScore}/100
        </Text>
        <Text style={styles.subheading}>BLUF</Text>
        <Text style={styles.line}>{data.bluf}</Text>
        <Text style={styles.subheading}>Key Findings</Text>
        {data.keyFindings.map((f) => (
          <View key={f.id} style={{ marginBottom: 4 }}>
            <Text>{f.title}</Text>
            <Text>{f.body}</Text>
            <Text>
              {f.agent} | Confidence {f.confidence} | Tier {f.sourceTier}
            </Text>
          </View>
        ))}
        <Text style={styles.subheading}>Scenarios</Text>
        {data.scenarios.map((s) => (
          <Text key={s.id} style={styles.line}>
            {s.type} {s.probability}% – {s.description}
          </Text>
        ))}
        <Text style={styles.subheading}>Agent Deep Dives</Text>
        {Object.entries(data.agents).map(([agent, block]) => (
          <Text key={agent} style={styles.line}>
            {agent}: {block.status.score ?? "–"}/100 | {block.metadata.model} | {block.metadata.latencyMs}ms
          </Text>
        ))}
        <Text style={styles.footer}>
          UNCLASSIFIED // OPEN SOURCE | Generated by Digital War Room | {data.generatedAt.toISOString()} | {data.version}
        </Text>
      </Page>
    </Document>
  );
}
